name: Deploy CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14.x

      - name: Cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
            ${{ runner.os }}-

      - run: yarn install
        name: Install Dependences

      - run: yarn build
        name: Run TypeScript Check

      - run: yarn add -D vercel
        name: Install vercel

      - run: yarn vercel whoami --token ${{ secrets.VERCEL_TOKEN }}
        name: Who am I

      - run: yarn vercel --token ${{ secrets.VERCEL_TOKEN }}
        name: Deploy to preview env

      - run: yarn vercel --prod --token ${{ secrets.VERCEL_TOKEN }}
        if: ${{ success() }}
        name: Deploy to production env
